# Deploy this Node.js project to the public folder
PROJECT_NAME=Beat-box
DEPLOY_PATH= $(HOME)/cmpt433/public/node/$(PROJECT_NAME)-copy

all: deploy

deploy:
	mkdir -p $(DEPLOY_PATH)
	chmod a+rwx $(DEPLOY_PATH)
	cp -r * $(DEPLOY_PATH)